### ISSUE TITLE
Connect GEOID to tidycensus attributes. Could be in its own script or with the data management one that is already started

### ISSUE THREAD

**Issue by Nateme16** [Nateme16/NEbeach-disparity#6]
# Connect GEOID's to census attributes
- leading zero issue 

Create attributes list of the census codes we want B102342......
- Wei-Lun's code could get us started. Find that code

Wanted variables:
- Median household income
- Hispanic or not
- Race - turned into %
- Ethnicities - turned into %
- Total populations that correspond to each of the question if we do %s
- average number of kids per household
- average size of households

**Comment by Nateme16** [comment]
Biggest project is getting the list of census variables. (B10002e etc.) we need to get for the whole list of GEOIDs. Kate?

**Comment by Nateme16** [comment]
> Biggest project is getting the list of census variables. (B10002e etc.) we need to get for the whole list of GEOIDs. Kate?

We have a list of variables now and have scripted using tidycensus for one at a time for our GEOID list so far.... We need to get the script to pull many variables from the census and put them in the right style (%, count, mean, median) that we want

**Comment by Eeburman** [comment]
Finished script to do this

**Comment by Nateme16** [comment]
AMAZING
